export const LIST_POST_INIT = "LIST_POST_INIT";
export const LIST_POST_SUCCESS = "LIST_POST_SUCCESS";
export const LIST_POST_FAIL = "LIST_POST_FAIL";

export const ADD_POST_INIT = "ADD_POST_INIT";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const UPDATE_POST_INIT = "UPDATE_POST_INIT";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";


export const DELETE_POST_INIT = "DELETE_POST_INIT";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

